### PR TITLE
Endogenous industry process heat

### PR DESCRIPTION
**Pull request by lisazeyen**
This should close PR #315 done by @millingermarkus 

Divides industrial heat demand into low, medium temperature and high temperature, with endogenous options to fulfill each sub-sector.

biomass, methane, electric boilers, heat pumps --> low temperature
biomass, methane, hydrogen --> medium temperature
methane, hydrogen --> high temperature

biomass and methane can be combined with carbon capture, including energy penalty for the carbon capture process.

Open ToDos:

- [x] share of medium and high temperature demand @millingermarkus , you set this to 0.3 and 0.7 respectively. Do you have a source?
- [ ] cost assumptions of industrial H2 combustion
- [x] must run condition for industrial heat supply, currently set to 0.8, does this make sense @fneum ?
- [x] Do we have all important options for low, medium and high temperature heat @fneum @nworbmot ?

### CODE REVIEW

**Comment by lisazeyen** [comment]
Useful to check also the assumptions of [DEA for industrial heat](https://ens.dk/en/our-services/projections-and-models/technology-data/technology-data-industrial-process-heat)

**Comment by millingermarkus** [comment]
Thanks @lisazeyen! Sorry, no source for the 0.3/0.7 assumption.
There are also electric options (plasma) for higher temperatures, and biomass can also be used for high T, but here the technology and cost uncertainties are larger (and nothing in DEA on this as far as I know). See e.g. http://dx.doi.org/10.1088/1748-9326/abbd02.

**Comment by lisazeyen** [comment]
> share of medium and high temperature: process heat temperature ranges by sector and country are shown in this paper [Quantification of the European industrial heat demand by branch and temperature level](https://doi.org/10.1002/er.3436) from 2015

I added the share of medium and high temperature heat based on this paper, table 3 for all EU28. In future, one should improve this assumption and adjust the shares depending on countries and sectors.

**Comment by fneum** [comment]
> must run condition for industrial heat supply, currently set to 0.8, does this make sense?

Do we actually need a must-run condition? The newly created heat buses have no heat storage and the mix of supply technologies must follow the constant load already. Hybrid solutions also make sense to me in industrial applications.

**Comment by fneum** [comment]
Regarding the shares of low/medium/high temperature, the cleaner solution would be to adapt the script `scripts/build_industry_sector_ratios.py`. The JRC-IDEES database will likely have all the necessary information to derive temperature levels for individual processes/subsectors.

```csv
MWh/tMaterial,Electric arc,DRI + Electric arc,Integrated s
elec,1.0813101126320095,1.4033101126320096,1.0208129006571
coal,0.0,0.0,1.3770042858681404,0.0,0.0,0.0,0.0,0.0,0.0,0.
coke,0.0,0.0,1.3117900264012818,0.0,0.0,0.0,0.0,0.0,0.0,0.
biomass,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1970
methane,0.22647645142596962,0.22647645142596962,0.22372625
hydrogen,0.0,1.7,0.0,0.00017266107692307694,0.0,0.0,6.5,-0
heat,0.0030178609567653556,0.0030178609567653556,0.0052507
naphtha,0.0,0.0,0.0,14.007836447394103,0.0,0.0,0.0,0.0,0.0
ammonia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.
process emission,0.027663169349199112,0.027663169349199112
process emission from feedstock,0.0,0.0,0.0,0.490384615384
```

**Pull request closed without merging**
