### PR TITLE
Replacing print statement with logging

### PR DESCRIPTION
**Pull request by virio-andreyana**
There are 30 print statement in pypsa-eur-sec. All of them are replaced with logging function. The justification of its level is as below:

### add_brownfield (in myopic)
- describing the function brownfield is running -> logger.debug
- describing the file with the new planning horizon to be used -> logger.info 
### add_existing_baseyear (in myopic)
- both are just describing an function that is going to run -> logger.debug
### build_energy_total
- all that is inside a loop function -> logger.debug
- missing data that is replaced with mean -> logger.info
### build_industrial_distribution_key
- The logger are only activated if an missing industrial site is found -> logger.debug
- if its still missing -> logger.warning
### build_industrial_production_per_country
- only informing which country have no ammonia demand -> logger.info
### build_population_layout
- the urbanization rate of each country -> logger.debug
### make_summeray
- `print(load * n.buses_t.marginal_price[buses])` result in large tables -> logger.debug
- describe file in which a summary is going to be made -> logger.info
- `print(networks_dict)` is a repeat from the previous logger, preferably removed
### plot_network
- `print(comp, costs)` result in large tables -> logger.debug
- `print("Warning!",item,"not in config/plotting/tech_colors")` -> logger.warning
- dropping non-busses -> logger.info
- dropping supply column -> logger.info
### plot_summary
- info on reasons why technology are dropped from the plot -> logger.info
- list of technologies that are dropped and its value -> logger.debug
- large tables -> logger.debug

### CODE REVIEW

**Review by FabianHofmann — COMMENTED** [review]
This looks great @virio-andreyana! One minor, picky thing, Could you harmonize the print so that the logs are starting with capital letters?

**Comment by virio-andreyana** [comment]
Done capitalized @FabianHofmann

**Comment by FabianHofmann** [comment]
Awesome @virio-andreyana

**Comment by FabianHofmann** [comment]
Ci is currently not working due to the jrc server not being responsive... Hopefully this will be solved shortly

**Comment by virio-andreyana** [comment]
plot_summary and plot_network has been updated @FabianHofmann. It worked in my test

**Review by fneum — APPROVED** [review]

**Pull request merged**
