### PR TITLE
Fix snakemake dependencies in carbon budget runs

### PR DESCRIPTION
**Pull request by energyLS**
This PR should resolve issues when running the model with myopic foresight with a carbon budget defined by the 'cb' option. The main issue was that the Snakemake object was not passed to imported functions in prepare_sector_network.py.

The following steps have been done:
1. move the snakemake dependencies of the affected functions to
compulsory function arguments (in build_energy_totals.py)
2. enter snakemake object values in the function calls
(build_energy_totals and prepare_sector_network)
3. add the new explicit file dependencies to the Snakefile at rule
prepare_sector_network 

Following other errors have occured and should be resolved:
- The folder created for carbon_budget_distribution.csv included the csv file in the path itself when creating the folders, hence an error occured. Solved in commit 
78d1c92d2cb278f745930bc71bd7de3fe75fc6d4

- The functions build_eurostat_co2 and build_co2_totals from build_energy_totals were missing the 'countries' argument. Solved in commit 
e9e0f3f180fede40d7f20a807ce331c0c4ca75a2

- The function build_eurostat_co2 expects the country argument as pd.Index to run the line https://github.com/PyPSA/pypsa-eur-sec/commit/25638e3d107c5cb8ef5f2ed3ec428b226d984b43#diff-132a8f9b549899b7eee1fc97ad04baa7c72a349df45041ba0bc1266e58813cacR640 successfully. Solved in commit 25638e3d107c5cb8ef5f2ed3ec428b226d984b43

Remaining questions:
- Should the file dependencies to the Snakefile at rule
prepare_sector_network added optionally if 'cb' keyword is in
{sector_opts} wildcard)?
- When running the full snakemake workflow, an error in plot_summary occurs: It tries to read 'results/run_name/csvs/countries.csv' which does not exist. This is no file specified as output in the Snakefile. Where should the 'countries.csv' (originally) be created? 

Once the remaining questions are resolved, this PR could be transformed from Draft to ready. Coding improvements are highly welcome. Sorry for the long text ;)

### CODE REVIEW

**Comment by energyLS** [comment]
Reason for error of missing "countries.csv" identified, the file creation was deleted in https://github.com/PyPSA/pypsa-eur-sec/commit/1fc1d2a17d982b2a8476b00670a7b836ed4b60bd#diff-d838d3f5e300ee6371584a10781b96424387d2186d355c6cf601433ac3e189cbL126

**Review by fneum — APPROVED** [review]
Thanks @energyLS, and sorry for taking so long to review. Like the compulsory function argument for snakemake. Nice workarouns.

**Comment by energyLS** [comment]
Hey @fneum thanks for approving. I will integrate your suggestions (release notes & retrieving countries from config.yaml) in approx. two weeks time.

**Comment by lisazeyen** [comment]
this can be closed since solved with #256

**Pull request closed without merging**
