### PR TITLE
Salt cavern potential

### PR DESCRIPTION
**Pull request by lisazeyen**
Hydrogen storage is split into underground storage for countries with geographical potential, otherwise hydrogen can be stored in overground steel tanks. Costs are changed from gas storage to corresponding hydrogen storage from technology database.
 Caution: input data gives only a potential per country (no high spatial resolution), upper limit for energy capacity of underground storage is distributed by population inside the country. The part 'e_nom_max' can be also removed, because probably storage capacities are larger than needed and distributing the storage capacity by population is maybe not a reasonable assumption.

### CODE REVIEW

**Comment by nworbmot** [comment]
Could we remove the redundancy of True/False and the capacity in the data file? I think removing the boolean and just later checking if the capacity is > 0 to get the boolean would avoid duplicated info.

**Comment by nworbmot** [comment]
I'll take care of it and push the changes to the master.

**Comment by nworbmot** [comment]
Hi @lisazeyen, one last thing, do we know what the source is for the H2 caverns? Is it https://doi.org/10.1016/j.ijhydene.2019.12.161?

**Comment by lisazeyen** [comment]
I am not sure. I took the csv from the transition_pathway repository from Kun. Maybe @martavp remembers the source?

**Comment by martavp** [comment]
Yes, the source for H2 salt caverns potential is Figure 8 in the paper mentioned by @nworbmot (https://doi.org/10.1016/j.ijhydene.2019.12.161?)

**Comment by nworbmot** [comment]
Thanks! I'll add the reference somewhere so it is documented.

**Pull request merged**
