### PR TITLE
Transition to atlite v0.2

### LINKED ISSUE #102: Update code for atlite >= v0.2
To maintain compatibility with the newest PyPSA-Eur environment with atlite>=0.2, a few adjustments might be necessary in PyPSA-Eur-Sec as well. See https://github.com/PyPSA/pypsa-eur/pull/224.

### PR DESCRIPTION
**Pull request by fneum**
closes #102

### CODE REVIEW

**Comment by fneum** [comment]
@FabianHofmann, here's the overview of the files affected by the new atlite version.

**Comment by FabianHofmann** [comment]
@fneum is this PR still actual/needed? (since you already tackled some atlite related code in the other PRs)

**Comment by fneum** [comment]
No, it was easier than expected. Sorry for not updating.

**Comment by FabianHofmann** [comment]
no worries ;)

**Pull request closed without merging**
